package org.apache.rocketmq.eventbridge.adapter.persistence.connect.mybatis.mapper;

import org.apache.rocketmq.eventbridge.domain.model.connection.EventConnection;
import org.apache.rocketmq.eventbridge.domain.model.connection.EventConnectionWithBLOBs;

public interface EventConnectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int insert(EventConnectionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int insertSelective(EventConnectionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    EventConnectionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventConnectionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EventConnectionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventConnection record);
}