/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.rocketmq.eventbridge.domain.model.connection;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class Connection implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.auth_type
     *
     * @mbggenerated
     */
    private String authorizationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.network_type
     *
     * @mbggenerated
     */
    private String networkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.account_id
     *
     * @return the value of event_connection.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.account_id
     *
     * @param accountId the value for event_connection.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.name
     *
     * @return the value of event_connection.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.name
     *
     * @param name the value for event_connection.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getAuthorizationType() {
        return authorizationType;
    }

    public void setAuthorizationType(String authorizationType) {
        this.authorizationType = authorizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.network_type
     *
     * @return the value of event_connection.network_type
     *
     * @mbggenerated
     */
    public String getNetworkType() {
        return networkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.network_type
     *
     * @param networkType the value for event_connection.network_type
     *
     * @mbggenerated
     */
    public void setNetworkType(String networkType) {
        this.networkType = networkType == null ? null : networkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.description
     *
     * @return the value of event_connection.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.description
     *
     * @param description the value for event_connection.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.gmt_create
     *
     * @return the value of event_connection.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.gmt_create
     *
     * @param gmtCreate the value for event_connection.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.gmt_modify
     *
     * @return the value of event_connection.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.gmt_modify
     *
     * @param gmtModify the value for event_connection.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Connection that = (Connection) o;

        return new EqualsBuilder().append(accountId, that.accountId).append(name, that.name).append(authorizationType, that.authorizationType).append(networkType, that.networkType).append(description, that.description).append(gmtCreate, that.gmtCreate).append(gmtModify, that.gmtModify).isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(accountId).append(name).append(authorizationType).append(networkType).append(description).append(gmtCreate).append(gmtModify).toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("accountId", accountId)
                .append("name", name)
                .append("authorizationType", authorizationType)
                .append("networkType", networkType)
                .append("description", description)
                .append("gmtCreate", gmtCreate)
                .append("gmtModify", gmtModify)
                .toString();
    }
}