/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.rocketmq.eventbridge.domain.model.connection;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import java.io.Serializable;

public class ConnectionWithBLOBs extends Connection implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.auth_parameters
     *
     * @mbggenerated
     */
    private String authParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.network_parameters
     *
     * @mbggenerated
     */
    private String networkParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.auth_parameters
     *
     * @return the value of event_connection.auth_parameters
     *
     * @mbggenerated
     */
    public String getAuthParameters() {
        return authParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.auth_parameters
     *
     * @param authParameters the value for event_connection.auth_parameters
     *
     * @mbggenerated
     */
    public void setAuthParameters(String authParameters) {
        this.authParameters = authParameters == null ? null : authParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.network_parameters
     *
     * @return the value of event_connection.network_parameters
     *
     * @mbggenerated
     */
    public String getNetworkParameters() {
        return networkParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.network_parameters
     *
     * @param networkParameters the value for event_connection.network_parameters
     *
     * @mbggenerated
     */
    public void setNetworkParameters(String networkParameters) {
        this.networkParameters = networkParameters == null ? null : networkParameters.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        ConnectionWithBLOBs that = (ConnectionWithBLOBs) o;

        return new EqualsBuilder().appendSuper(super.equals(o)).append(authParameters, that.authParameters).append(networkParameters, that.networkParameters).isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).appendSuper(super.hashCode()).append(authParameters).append(networkParameters).toHashCode();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authParameters=").append(authParameters);
        sb.append(", networkParameters=").append(networkParameters);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}