package org.apache.rocketmq.eventbridge.domain.model.connection;

import java.io.Serializable;

public class EventConnectionWithBLOBs extends EventConnection implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.auth_parameters
     *
     * @mbggenerated
     */
    private String authParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_connection.network_parameters
     *
     * @mbggenerated
     */
    private String networkParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.auth_parameters
     *
     * @return the value of event_connection.auth_parameters
     *
     * @mbggenerated
     */
    public String getAuthParameters() {
        return authParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.auth_parameters
     *
     * @param authParameters the value for event_connection.auth_parameters
     *
     * @mbggenerated
     */
    public void setAuthParameters(String authParameters) {
        this.authParameters = authParameters == null ? null : authParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_connection.network_parameters
     *
     * @return the value of event_connection.network_parameters
     *
     * @mbggenerated
     */
    public String getNetworkParameters() {
        return networkParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_connection.network_parameters
     *
     * @param networkParameters the value for event_connection.network_parameters
     *
     * @mbggenerated
     */
    public void setNetworkParameters(String networkParameters) {
        this.networkParameters = networkParameters == null ? null : networkParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EventConnectionWithBLOBs other = (EventConnectionWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAuthType() == null ? other.getAuthType() == null : this.getAuthType().equals(other.getAuthType()))
            && (this.getNetworkType() == null ? other.getNetworkType() == null : this.getNetworkType().equals(other.getNetworkType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()))
            && (this.getAuthParameters() == null ? other.getAuthParameters() == null : this.getAuthParameters().equals(other.getAuthParameters()))
            && (this.getNetworkParameters() == null ? other.getNetworkParameters() == null : this.getNetworkParameters().equals(other.getNetworkParameters()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAuthType() == null) ? 0 : getAuthType().hashCode());
        result = prime * result + ((getNetworkType() == null) ? 0 : getNetworkType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        result = prime * result + ((getAuthParameters() == null) ? 0 : getAuthParameters().hashCode());
        result = prime * result + ((getNetworkParameters() == null) ? 0 : getNetworkParameters().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_connection
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authParameters=").append(authParameters);
        sb.append(", networkParameters=").append(networkParameters);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}