package org.apache.rocketmq.eventbridge.domain.model.apidestination;

import java.io.Serializable;
import java.util.Date;

public class EventApiDestination implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.protocol
     *
     * @mbggenerated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.connection_name
     *
     * @mbggenerated
     */
    private String connectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.invocation_rate_limit_per_second
     *
     * @mbggenerated
     */
    private Integer invocationRateLimitPerSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_api_destination.api_params
     *
     * @mbggenerated
     */
    private String apiParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.id
     *
     * @return the value of event_api_destination.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.id
     *
     * @param id the value for event_api_destination.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.name
     *
     * @return the value of event_api_destination.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.name
     *
     * @param name the value for event_api_destination.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.protocol
     *
     * @return the value of event_api_destination.protocol
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.protocol
     *
     * @param protocol the value for event_api_destination.protocol
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.connection_name
     *
     * @return the value of event_api_destination.connection_name
     *
     * @mbggenerated
     */
    public String getConnectionName() {
        return connectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.connection_name
     *
     * @param connectionName the value for event_api_destination.connection_name
     *
     * @mbggenerated
     */
    public void setConnectionName(String connectionName) {
        this.connectionName = connectionName == null ? null : connectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.invocation_rate_limit_per_second
     *
     * @return the value of event_api_destination.invocation_rate_limit_per_second
     *
     * @mbggenerated
     */
    public Integer getInvocationRateLimitPerSecond() {
        return invocationRateLimitPerSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.invocation_rate_limit_per_second
     *
     * @param invocationRateLimitPerSecond the value for event_api_destination.invocation_rate_limit_per_second
     *
     * @mbggenerated
     */
    public void setInvocationRateLimitPerSecond(Integer invocationRateLimitPerSecond) {
        this.invocationRateLimitPerSecond = invocationRateLimitPerSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.description
     *
     * @return the value of event_api_destination.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.description
     *
     * @param description the value for event_api_destination.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.gmt_create
     *
     * @return the value of event_api_destination.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.gmt_create
     *
     * @param gmtCreate the value for event_api_destination.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.gmt_modify
     *
     * @return the value of event_api_destination.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.gmt_modify
     *
     * @param gmtModify the value for event_api_destination.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_api_destination.api_params
     *
     * @return the value of event_api_destination.api_params
     *
     * @mbggenerated
     */
    public String getApiParams() {
        return apiParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_api_destination.api_params
     *
     * @param apiParams the value for event_api_destination.api_params
     *
     * @mbggenerated
     */
    public void setApiParams(String apiParams) {
        this.apiParams = apiParams == null ? null : apiParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EventApiDestination other = (EventApiDestination) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getProtocol() == null ? other.getProtocol() == null : this.getProtocol().equals(other.getProtocol()))
            && (this.getConnectionName() == null ? other.getConnectionName() == null : this.getConnectionName().equals(other.getConnectionName()))
            && (this.getInvocationRateLimitPerSecond() == null ? other.getInvocationRateLimitPerSecond() == null : this.getInvocationRateLimitPerSecond().equals(other.getInvocationRateLimitPerSecond()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()))
            && (this.getApiParams() == null ? other.getApiParams() == null : this.getApiParams().equals(other.getApiParams()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getProtocol() == null) ? 0 : getProtocol().hashCode());
        result = prime * result + ((getConnectionName() == null) ? 0 : getConnectionName().hashCode());
        result = prime * result + ((getInvocationRateLimitPerSecond() == null) ? 0 : getInvocationRateLimitPerSecond().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        result = prime * result + ((getApiParams() == null) ? 0 : getApiParams().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", protocol=").append(protocol);
        sb.append(", connectionName=").append(connectionName);
        sb.append(", invocationRateLimitPerSecond=").append(invocationRateLimitPerSecond);
        sb.append(", description=").append(description);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", apiParams=").append(apiParams);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}