package org.apache.rocketmq.eventbridge.adapter.persistence.apidestination.mybatis.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.rocketmq.eventbridge.domain.model.apidestination.EventApiDestination;

import java.util.List;

public interface EventApiDestinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int insert(EventApiDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int insertSelective(EventApiDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    EventApiDestination selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    List<EventApiDestination> listApiDestinations(@Param("accountId") String accountId, @Param("name") String name,
                                                 @Param("nextToken") int nextToken, @Param("maxResults") int maxResults);

    /**
     * 通过用户id和名称查询
     * @param accountId
     * @param name
     * @return
     */
    EventApiDestination selectByAccountIdAndName(@Param("accountId") String accountId, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventApiDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int updateByNameAndAccountId(EventApiDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EventApiDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_api_destination
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventApiDestination record);

    /**
     * 根据用户Id和名称删除数据
     * @param accountId
     * @param name
     * @return
     */
    int deleteByAccountIdAndName(@Param("accountId") String accountId, @Param("name") String name);

    /**
     *
     * @param accountId
     * @param name
     * @return
     */
    int getApiDestinationCount(@Param("accountId") String accountId, @Param("name") String name);
}